### ISSUE TITLE
Remove PomCreator

### ISSUE THREAD

**Issue by klaushauschild1984** [AGETO/hybris-maven-plugin#12]
There is a CreatePomTask that will use the PomCreator. The PomCreator was introduced to reuse the functionality of the CreatePomTask. That use case is not any more valid. Becaus of that the PomCreator could be removed.

**Comment by Chief-of-Zetten** [comment]
done.

**Comment by klaushauschild1984** [comment]
Now the functionality is gone. It has to be MOVED to the CreatePomTasks!

**Comment by klaushauschild1984** [comment]
Now its done like I wanted.
