### ISSUE TITLE
Restructure basic extensions

### ISSUE THREAD

**Issue by Chief-of-Zetten** [AGETO/hybris-maven-plugin#14]
https://github.com/AGETO/hybris-maven-plugin/wiki/Basic-extensions

**Comment by klaushauschild1984** [comment]
The hybris extensions will now be restructured.

Extraction of the source code and dependencies are already missing

**Comment by klaushauschild1984** [comment]
The restructure, model generation and compilation of basic extensions is now working. This issue will be closed.
While ficing this I leaved many TODOs within the sources. This problems have to be solved in other issues.
