### ISSUE TITLE
Resolve external dependencies

### ISSUE THREAD

**Issue by klaushauschild1984** [AGETO/hybris-maven-plugin#26]
Every hybris extension has a lib folder containing additional libraries. It looks like that they all comes from maven central repository.
Use the REST api of search.maven.org to determine the GAV parameters of each library.

For example commons-configuration-1.7:
`http://search.maven.org/solrsearch/select?q=a:%22fastutil%22%20AND%20v:%226.5.6%22%20AND%20p:%22jar%22&rows=20&wt=json`

**Comment by klaushauschild1984** [comment]
The basic functionality is there.
If it is not possible to determine the maven coordinates of a library it has to be installed localy.

**Comment by Chief-of-Zetten** [comment]
use declared dependencies from externel-dependencies.xml

**Comment by klaushauschild1984** [comment]
There has to be a combined way to solve this. For producing the extensions pom.xml it is easier to take the external-dependencies.xml as source. But it is also possible to simply place an additional library just as file in the lib folder.
To resolve the extensions dependencies both sources (jar files in lib and external-dependencies.xml) has to be combined and processed.
The external-dependencies.xml is necessary for the contained dependency exclusions.

**Comment by klaushauschild1984** [comment]
The source for dependency resolving is external-dependencies.xml.
If the dependency is resolvable it will taken as it is. If not it will be installed locally from lib/ folder.
