### ISSUE TITLE
split extension "hac" into backend and frontend modules

### ISSUE THREAD

**Issue by Chief-of-Zetten** [AGETO/hybris-maven-plugin#35]
Copy folder "web" in "hac" into separate folder "hac-web" (contains directory src/main/resources)

**Comment by klaushauschild1984** [comment]
For clarification:
We differ two extension type: core and web. A web extension has always a core part.
All care stuff is located in extensions root without web folder. All Content of web folder represents the web part. It looks like the same layout as a core extension.
For example hac is one of the basic extensions with a web part. It will split in two maven artifacts: hac and hac-web. Their content should look like:
- hac
  - [as it is without web folder]
- hac-web
  - src
    - main
      - resources
        - [content web/webroot/WEB-INF/classes]
      - webapp
        - [content of web/webroot except compiled classes]
  - pom.xml
    - `<dependencies>`
    - `<dependency>de.hybris:core:[hybris-version]</dependency>`

**Comment by Chief-of-Zetten** [comment]
for some reason, the content of hac-web in hybris reactor dir is not getting copied to the hybris fake structure.
