### ISSUE TITLE
Resolve compilation error of extension "mediaweb"

### ISSUE THREAD

**Issue by Chief-of-Zetten** [AGETO/hybris-maven-plugin#47]
When running the code generator it produces a compilation error for extension "mediaweb". This should be resolved.

**Comment by klaushauschild1984** [comment]
The stacktrace with details of the compilation error would be nice.

**Comment by klaushauschild1984** [comment]
The compilation errors are caused by missing dependencies to Mockito and hybris bootstrap. I discovered that ever extension misses its implicit dependency to core.

**Comment by Chief-of-Zetten** [comment]
As this site
[http://stackoverflow.com/questions/9898749/using-string-array-in-hashmap-java](url)
indicate, java.util.Map can store Arrays as values, so maybe the compilation error in Line 148 of class XSSFilterTest is caused by maven not recognizing that there's an array stored in the map.

**Comment by Chief-of-Zetten** [comment]
getParameterMap of Interface ServletRequest returns a Map of Type `<String, String[]>`
http://docs.oracle.com/javaee/6/api/javax/servlet/ServletRequest.html#getParameterMap()

**Comment by Chief-of-Zetten** [comment]
Trying to run the code generator returns following error message for XSSFilterTest:
`org.apache.commons.logging.LogConfigurationException: User-specified log class 'de.hybris.platform.util.logging.CommonsHybrisLog4jWrapper' cannot be found or is not useable.`

**Comment by Chief-of-Zetten** [comment]
I found out, that the searched class is contained in "coreserver.jar".

**Comment by Chief-of-Zetten** [comment]
Adding log4j.xml in core/src/main/resources with content

`<?xml version="1.0" encoding="UTF-8" ?>`
`<!DOCTYPE log4j:configuration SYSTEM "log4j.dtd">`
`<log4j:configuration xmlns:log4j="http://jakarta.apache.org/log4j/">`
`<appender name="console" class="org.apache.log4j.ConsoleAppender">`
`<param name="Target" value="System.out"/>`
`<layout class="org.apache.log4j.PatternLayout">`
`<param name="ConversionPattern" value="%-5p %c{1} - %m%n"/>`
`</layout>`
`</appender>`
`<root>`
`<priority value ="debug" />`
`<appender-ref ref="console" />`
`</root>`
`</log4j:configuration>`

seems to resolve the first of the errors displayed when trying to compile, but it does not affect the others.

**Comment by Chief-of-Zetten** [comment]
Compile error seems to be resolved.
