### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by Loki-Afro** [AGETO/hybris-maven-plugin#7]
How to build the project? This is essential for  gh-5

> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 6.773 s
> [INFO] Finished at: 2016-08-11T10:22:40+02:00
> [INFO] Final Memory: 14M/202M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal on project hybris-maven-plugin: Could not resolve dependencies for project com.divae.ageto:hybris-maven-plugin:maven-plugin:0.0-SNAPSHOT: Could not find artifact de.hybris:bootstrap:jar:5.5.1.1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by klaushauschild1984** [comment]
Now the plugin could be build without special trickery
